### ISSUE TITLE
build出错：countref: unbound identifier

### ISSUE THREAD

**Issue by Hcoleyh** [chihyang/eopl3_zh#1]
请问如何构建？我用 DrRacket 打开 `eopl.scrbl` Scribble PDF 出现以下错误:
`style.rkt:203:35: countref: unbound identifier in: countref`

**Comment by chihyang** [comment]
Thanks for your interest. The build requires a private scribble and modifications to other packages. There's no plan to release them. A link to PDF may be released in the future.
