### ISSUE TITLE
一个错误

### ISSUE THREAD

**Issue by makiorgakki** [chihyang/eopl3_zh#2]
style.rkt:203:35: countref: unbound identifier in: countref
这个脚本有这个错误

**Comment by chihyang** [comment]
Thanks for your interest. See issue #1 for details.

In issue #1, I said:
> The build requires a private scribble and modifications to other packages. There's no plan to release them. A link to PDF may be released in the future.

In fact, the "private" scribble is not really private. It's a PR to the official scribble (https://github.com/racket/scribble/pull/242). But I don't think it will be merged. Maybe the official maintainer thinks it's too specific to the PDF format. If you really want to compile a PDF, you can take a look at that PR and try to install the customized scribble. But there's no plan to release a doc on compiling. A PDF may be released in the future.
